### ISSUE TITLE
Document test failed when using memdb

### ISSUE THREAD

**Issue by JOOHOJANG** [yorkie-team/yorkie#1018]
**Description**:
I found [this TC](https://github.com/yorkie-team/yorkie/blob/0871fac98488c7de245f19a395c0be1d0317ac19/test/integration/document_test.go#L814) fails when using memdb, but it passes when using mongoDB. (`main` branch)
CI cannot detect it because its using mongoDB when testing.

```
--- FAIL: TestDocumentWithProjects (0.65s)
    --- FAIL: TestDocumentWithProjects/includeSnapshot_test (0.01s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 4213 [running]:
testing.tRunner.func1.2({0x101ec9e00, 0xc002597f50})
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1632 +0x2c4
testing.tRunner.func1()
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1635 +0x47c
panic({0x101ec9e00?, 0xc002597f50?})
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x124
github.com/yorkie-team/yorkie/test/integration.TestDocumentWithProjects.func3(0xc0025a6340)
        /Users/user/Documents/yorkie/test/integration/document_test.go:828 +0x3b8
testing.tRunner(0xc0025a6340, 0xc003903500)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1690 +0x188
created by testing.(*T).Run in goroutine 4062
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1743 +0x5e4
FAIL    github.com/yorkie-team/yorkie/test/integration  26.292s
FAIL
make: *** [test] Error 1
```
**Why**:

**Comment by raararaara** [comment]
When `PageSize` is set to 0, MongoDB returns all results. ([Official Documentation](https://www.mongodb.com/docs/drivers/go/v1.11/fundamentals/crud/read-operations/limit/#limit)) 

Unlike MongoDB, memDB does not apply any specific logic to set a limit. Currently, the implementation in memDB stops iteration when `len(docInfo)` is greater than or equal to `PageSize`.

https://github.com/yorkie-team/yorkie/blob/0871fac98488c7de245f19a395c0be1d0317ac19/server/backend/database/memory/database.go#L1355-L1365

As a result, no `docInfo` is returned, which seems to have caused the 'index out of range' issue.
