### ISSUE TITLE
Remove panic from server code

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#50]
Currently, panic is called when an exception such as an error occurs in the server code. The server goes down, but it is easier to grasp the error situation.

However, in the production environment, it should be changed to return an error instead of panic so that the server does not stop.

**Comment by gmlwo530** [comment]
Could i try this issue?

**Comment by hackerwins** [comment]
@gmlwo530 Sure. Let me know if you have any questions.

**Comment by semin-park** [comment]
While playing around with the js-sdk, I've experienced this panic. It occurred while I was debugging in the developer's console. I'm not sure how this happened, but maybe I might have set a breakpoint somewhere I'm not supposed to..
```
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).findFloorNodePreferToLeft
yorkie    |     /app/pkg/document/json/rga_tree_split.go:282
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).findNodeWithSplit
yorkie    |     /app/pkg/document/json/rga_tree_split.go:266
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).edit
yorkie    |     /app/pkg/document/json/rga_tree_split.go:371
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*Text).Edit
yorkie    |     /app/pkg/document/json/text.go:152
yorkie    | github.com/yorkie-team/yorkie/pkg/document/operation.(*Edit).Execute
yorkie    |     /app/pkg/document/operation/edit.go:56
yorkie    | github.com/yorkie-team/yorkie/pkg/document/change.(*Change).Execute
yorkie    |     /app/pkg/document/change/change.go:48
yorkie    | github.com/yorkie-team/yorkie/pkg/document.(*Document).ApplyChangePack
yorkie    |     /app/pkg/document/document.go:112
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.pullSnapshot
yorkie    |     /app/yorkie/packs/pack_service.go:291
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.pullPack
yorkie    |     /app/yorkie/packs/pack_service.go:189
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.PushPull
yorkie    |     /app/yorkie/packs/pack_service.go:59
yorkie    | github.com/yorkie-team/yorkie/yorkie/rpc.(*Server).AttachDocument
yorkie    |     /app/yorkie/rpc/server.go:190
yorkie    | github.com/yorkie-team/yorkie/api._Yorkie_AttachDocument_Handler.func1
yorkie    |     /app/api/yorkie.pb.go:3662
yorkie    | github.com/yorkie-team/yorkie/yorkie/rpc.unaryInterceptor
yorkie    |     /app/yorkie/rpc/interceptors.go:35
yorkie    | github.com/yorkie-team/yorkie/api._Yorkie_AttachDocument_Handler
yorkie    |     /app/api/yorkie.pb.go:3664
yorkie    | google.golang.org/grpc.(*Server).processUnaryRPC
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995
yorkie    | google.golang.org/grpc.(*Server).handleStream
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275
yorkie    | google.golang.org/grpc.(*Server).serveStreams.func1.1
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710
yorkie    | panic: the node of the given id should be found
yorkie    |
yorkie    | goroutine 8 [running]:
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).findFloorNodePreferToLeft(0xc0004982c0, 0xc0004becf0, 0xc0004bece0)
yorkie    |     /app/pkg/document/json/rga_tree_split.go:283 +0x1f8
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).findNodeWithSplit(0xc0004982c0, 0xc000483480, 0xc00048b6a0, 0xc000100000, 0x7f71ebd96108)
yorkie    |     /app/pkg/document/json/rga_tree_split.go:266 +0x8a
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*RGATreeSplit).edit(0xc0004982c0, 0xc000483460, 0xc000483480, 0xc0004876b0, 0xe3f080, 0xc0004bece0, 0xc00048b6a0, 0x18, 0x413e9e)
yorkie    |     /app/pkg/document/json/rga_tree_split.go:371 +0x5a
yorkie    | github.com/yorkie-team/yorkie/pkg/document/json.(*Text).Edit(0xc0004c3ce0, 0xc000483460, 0xc000483480, 0xc0004876b0, 0x0, 0x0, 0xc00048b6a0, 0xc000498360, 0xc000498380)
yorkie    |     /app/pkg/document/json/text.go:152 +0xc1
yorkie    | github.com/yorkie-team/yorkie/pkg/document/operation.(*Edit).Execute(0xc00048c500, 0xc000498380, 0xc00020f228, 0xad0acd)
yorkie    |     /app/pkg/document/operation/edit.go:56 +0xf2
yorkie    | github.com/yorkie-team/yorkie/pkg/document/change.(*Change).Execute(0xc00048c540, 0xc000498380, 0x0, 0x0)
yorkie    |     /app/pkg/document/change/change.go:48 +0x70
yorkie    | github.com/yorkie-team/yorkie/pkg/document.(*Document).ApplyChangePack(0xc000483300, 0xc00020f4c0, 0xc00003cb70, 0xaf0d28202e83d5f)
yorkie    |     /app/pkg/document/document.go:112 +0x3cf
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.pullSnapshot(0xe3d080, 0xc00003cb70, 0xc0000342d0, 0xc0000e6070, 0xc000096280, 0xc0000345a0, 0xc00003b030, 0x453, 0x40dc06, 0xc0000945b0, ...)
yorkie    |     /app/yorkie/packs/pack_service.go:291 +0x65f
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.pullPack(0xe3d080, 0xc00003cb70, 0xc0000342d0, 0xc0000e6070, 0xc000096280, 0xc0000345a0, 0xc00003b030, 0x453, 0x0, 0x0, ...)
yorkie    |     /app/yorkie/packs/pack_service.go:189 +0x2cf
yorkie    | github.com/yorkie-team/yorkie/yorkie/packs.PushPull(0xe3d080, 0xc00003cb70, 0xc0000342d0, 0xc0000e6070, 0xc000096280, 0xc0000345a0, 0x1, 0xc0000e6070, 0xc000096280)
yorkie    |     /app/yorkie/packs/pack_service.go:59 +0x102
yorkie    | github.com/yorkie-team/yorkie/yorkie/rpc.(*Server).AttachDocument(0xc00000ee00, 0xe3d080, 0xc00003cb70, 0xc000080300, 0x0, 0x0, 0x0)
yorkie    |     /app/yorkie/rpc/server.go:190 +0xaaf
yorkie    | github.com/yorkie-team/yorkie/api._Yorkie_AttachDocument_Handler.func1(0xe3d080, 0xc00003cb70, 0xc54980, 0xc000080300, 0xc000080300, 0x0, 0x0, 0xc00006b9a8)
yorkie    |     /app/api/yorkie.pb.go:3662 +0x86
yorkie    | github.com/yorkie-team/yorkie/yorkie/rpc.unaryInterceptor(0xe3d080, 0xc00003cb70, 0xc54980, 0xc000080300, 0xc00000f040, 0xc00000f060, 0xc00006ba48, 0x4f71a8, 0xc270c0, 0xc00003cb70)
yorkie    |     /app/yorkie/rpc/interceptors.go:35 +0x9b
yorkie    | github.com/yorkie-team/yorkie/api._Yorkie_AttachDocument_Handler(0xc377c0, 0xc00000ee00, 0xe3d080, 0xc00003cb70, 0xc000033620, 0xcbc580, 0xe3d080, 0xc00003cb70, 0xc00009c600, 0x36)
yorkie    |     /app/api/yorkie.pb.go:3664 +0x14b
yorkie    | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c0000, 0xe44440, 0xc000318180, 0xc0000e4000, 0xc00003c7e0, 0x1356f70, 0x0, 0x0, 0x0)
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
yorkie    | google.golang.org/grpc.(*Server).handleStream(0xc0000c0000, 0xe44440, 0xc000318180, 0xc0000e4000, 0x0)
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd3d
yorkie    | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00030e050, 0xc0000c0000, 0xe44440, 0xc000318180, 0xc0000e4000)
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xa1
yorkie    | created by google.golang.org/grpc.(*Server).serveStreams.func1
yorkie    |     /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```
